airbnb:
  outputs:
    dev:
      type: snowflake
      account: vwfetcf-da36679
      user: dbt

      role: TRANSFORM
      private_key_path: "/home/nikola/.ssh/rsa_key_enc.p8"
      private_key_passphrase: q

      database: AIRBNB
      schema: DEV
      threads: 1
      warehouse: COMPUTE_WH
  target: dev
